// <auto-generated />
namespace TaskManagerAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_tasks_list_to_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tasks_list_to_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202002070959056_add_tasks_list_to_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
