// <auto-generated />
namespace TaskManagerAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_navigation_field_on_task : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_navigation_field_on_task));
        
        string IMigrationMetadata.Id
        {
            get { return "202002071134295_added_navigation_field_on_task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
